# Generated by Django 3.1.7 on 2021-05-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0013_auto_20210503_1659'),
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customers')),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.deliverers')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderExecution.order')),
            ],
        ),
    ]
