# Generated by Django 3.1.7 on 2021-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderExecution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverer_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting for restaurant', 'Pending Restaurant'), ('Waiting for deliverer', 'Pending Delivery'), ('In progress', 'Inprogress'), ('Declined', 'Declined'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
