# Generated by Django 3.1.7 on 2021-05-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_auto_20210529_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
