# Generated by Django 3.1.7 on 2021-04-25 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_pendingrestaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 55, 55, 341097, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 55, 55, 341050, tzinfo=utc)),
        ),
    ]
