# Generated by Django 3.1.7 on 2021-04-25 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210425_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 56, 7, 536553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 56, 7, 536525, tzinfo=utc)),
        ),
    ]
