# Generated by Django 3.1.7 on 2021-04-25 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210425_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrestaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 59, 18, 335882, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pendingrestaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 59, 18, 335836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 59, 18, 334840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 25, 14, 59, 18, 334795, tzinfo=utc)),
        ),
    ]
