# Generated by Django 3.1.7 on 2021-05-03 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20210503_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrestaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 3, 16, 56, 3, 462430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pendingrestaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 3, 16, 56, 3, 462410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='close_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 3, 16, 56, 3, 461967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='open_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 3, 16, 56, 3, 461940, tzinfo=utc)),
        ),
    ]
