# Generated by Django 3.1.7 on 2021-05-03 18:52

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20210503_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverers',
            name='status',
            field=models.CharField(default=Users.models.DelivererStatus['NOTAVAILABLE'], max_length=16),
        ),
    ]
