# Generated by Django 3.1.7 on 2021-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20210509_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
