# Generated by Django 3.1.7 on 2021-05-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20210509_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverers',
            name='status',
        ),
    ]
