# Generated by Django 3.1.7 on 2021-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_deliverers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverers',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Notavailable'), ('Available', 'Available'), ('Busy', 'Busy')], default='Unavailable', max_length=16),
        ),
    ]
