# Generated by Django 3.1.7 on 2021-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rate_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
