# Generated by Django 3.1.7 on 2021-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_auto_20210525_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverers',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverers',
            name='rate_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverers',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
